services:

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_GID=999 
      - DATABASE_URL=file:/app/data/configs/db.sqlite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - homarr_configs:/app/data/configs
      - homarr_icons:/app/public/icons
    ports:
      - '7575:7575'

volumes:
  homarr_configs:
  homarr_icons: